# .yarnrc.yml
nodeLinker: node-modules

# Keep installs deterministic and workspace-friendly
nmHoistingLimits: workspaces

# Optional: prevents Yarn from trying to be clever with unplugging
# (safe to omit, but helps keep behavior consistent)
enableGlobalCache: false